<?php

declare(strict_types=1);

namespace App\Core;

use PDO;
use PDOException;
use PDOStatement;
use RuntimeException;

/**
 * Singleton Database class using PDO.
 *
 * Guarantees a single connection instance per request lifecycle.
 * Provides secure prepared-statement execution and transaction helpers.
 *
 * PSR-12 compliant.
 */
class Database
{
    private static ?Database $instance = null;
    private PDO $connection;
    private string $driver;

    /**
     * Private constructor — enforces Singleton pattern.
     * Reads config from /config/db.php and opens MySQL or PostgreSQL connection.
     */
    private function __construct()
    {
        $config = require BASE_PATH . '/config/db.php';
        $this->driver = $config['driver'] ?? 'mysql';

        if ($this->driver === 'pgsql') {
            $dsn = sprintf(
                'pgsql:host=%s;port=%s;dbname=%s;sslmode=require',
                $config['host'],
                $config['port'],
                $config['dbname']
            );
        } else {
            $dsn = sprintf(
                'mysql:host=%s;port=%s;dbname=%s;charset=%s',
                $config['host'],
                $config['port'],
                $config['dbname'],
                $config['charset'] ?? 'utf8mb4'
            );
        }

        $options = [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
            PDO::ATTR_STRINGIFY_FETCHES   => false,
        ];

        try {
            $this->connection = new PDO(
                $dsn,
                $config['user'],
                $config['password'],
                $options
            );
        } catch (PDOException $e) {
            error_log('[DB] Connection failed: ' . $e->getMessage());
            http_response_code(503);
            header('Content-Type: application/json');
            $isDev = ($_ENV['APP_ENV'] ?? '') !== 'production';
            $msg = 'خدمة قاعدة البيانات غير متاحة حالياً.';
            if ($isDev) {
                $msg .= ' | ' . $e->getMessage();
            }
            die(json_encode(['error' => $msg]));
        }
    }

    /** Returns 'mysql' or 'pgsql'. */
    public function getDriver(): string
    {
        return $this->driver;
    }

    /**
     * Prevent cloning — Singleton must not be duplicated.
     */
    private function __clone(): void
    {
    }

    /**
     * Prevent unserialization — would bypass the Singleton constructor.
     *
     * @throws RuntimeException Always.
     */
    public function __wakeup(): void
    {
        throw new RuntimeException('Cannot unserialize a Singleton.');
    }

    /**
     * Return the single Database instance, creating it on first call.
     */
    public static function getInstance(): Database
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    /**
     * Expose the raw PDO connection for edge-cases (transactions, etc.).
     */
    public function getConnection(): PDO
    {
        return $this->connection;
    }

    /**
     * Prepare and execute a parameterised query.
     *
     * All user-supplied values MUST be passed via $params — never interpolated
     * into $sql directly.
     *
     * @param  string  $sql    SQL with named (:name) or positional (?) placeholders
     * @param  array   $params Parameter map or list
     * @return PDOStatement    Executed statement (call ->fetch() / ->fetchAll() on it)
     */
    public function query(string $sql, array $params = []): PDOStatement
    {
        $stmt = $this->connection->prepare($sql);
        $stmt->execute($params);
        return $stmt;
    }

    /**
     * Return the auto-increment ID generated by the last INSERT.
     * For PostgreSQL, uses lastval() when no sequence name is given.
     */
    public function lastInsertId(?string $sequence = null): int
    {
        if ($this->driver === 'pgsql') {
            if ($sequence !== null) {
                return (int) $this->connection->lastInsertId($sequence);
            }
            $stmt = $this->connection->query('SELECT lastval()');
            $row = $stmt->fetch(\PDO::FETCH_NUM);
            return (int) ($row[0] ?? 0);
        }
        return (int) $this->connection->lastInsertId();
    }

    // -------------------------------------------------------------------------
    // Transaction helpers
    // -------------------------------------------------------------------------

    /**
     * Begin a database transaction.
     */
    public function beginTransaction(): bool
    {
        return $this->connection->beginTransaction();
    }

    /**
     * Commit the current transaction.
     */
    public function commit(): bool
    {
        return $this->connection->commit();
    }

    /**
     * Roll back the current transaction.
     */
    public function rollBack(): bool
    {
        return $this->connection->rollBack();
    }
}
